export const ACCESOS_LIST_REQUEST = "ACCESOS_LIST_REQUEST";
export const ACCESOS_LIST_SUCCESS = "ACCESOS_LIST_SUCCESS";
export const ACCESOS_LIST_FAIL = "ACCESOS_LIST_FAIL";
export const ACCESOS_LIST_RESET = "ACCESOS_LIST_RESET";