export const ASIGNACIONES_LIST_REQUEST = "ASIGNACIONES_LIST_REQUEST";
export const ASIGNACIONES_LIST_SUCCESS = "ASIGNACIONES_LIST_SUCCESS";
export const ASIGNACIONES_LIST_FAIL = "ASIGNACIONES_LIST_FAIL";
export const ASIGNACIONES_LIST_RESET = "ASIGNACIONES_LIST_RESET";

export const ASIGNACIONES_CREATE_REQUEST = "ASIGNACIONES_CREATE_REQUEST";
export const ASIGNACIONES_CREATE_SUCCESS = "ASIGNACIONES_CREATE_SUCCESS";
export const ASIGNACIONES_CREATE_FAIL = "ASIGNACIONES_CREATE_FAIL";

export const ASIGNACIONES_DETAILS_REQUEST = "ASIGNACIONES_DETAILS_REQUEST";
export const ASIGNACIONES_DETAILS_SUCCESS = "ASIGNACIONES_DETAILS_SUCCESS";
export const ASIGNACIONES_DETAILS_FAIL = "ASIGNACIONES_DETAILS_FAIL";
export const ASIGNACIONES_DETAILS_RESET = "ASIGNACIONES_DETAILS_RESET";

export const ASIGNACIONES_UPDATE_REQUEST = "ASIGNACIONES_UPDATE_REQUEST";
export const ASIGNACIONES_UPDATE_SUCCESS = "ASIGNACIONES_UPDATE_SUCCESS";
export const ASIGNACIONES_UPDATE_FAIL = "ASIGNACIONES_UPDATE_FAIL";
export const ASIGNACIONES_UPDATE_RESET = "ASIGNACIONES_UPDATE_RESET";

export const ASIGNACIONES_DELETE_REQUEST = "ASIGNACIONES_DELETE_REQUEST";
export const ASIGNACIONES_DELETE_SUCCESS = "ASIGNACIONES_DELETE_SUCCESS";
export const ASIGNACIONES_DELETE_FAIL = "ASIGNACIONES_DELETE_FAIL";
export const ASIGNACIONES_DELETE_RESET = "ASIGNACIONES_DELETE_RESET";

export const ASIGNACIONES_ACTIVATE_REQUEST = "ASIGNACIONES_ACTIVATE_REQUEST";
export const ASIGNACIONES_ACTIVATE_SUCCESS = "ASIGNACIONES_ACTIVATE_SUCCESS";
export const ASIGNACIONES_ACTIVATE_FAIL = "ASIGNACIONES_ACTIVATE_FAIL";