export const BODEGA_LIST_REQUEST = "BODEGA_LIST_REQUEST";
export const BODEGA_LIST_SUCCESS = "BODEGA_LIST_SUCCESS";
export const BODEGA_LIST_FAIL = "BODEGA_LIST_FAIL";
export const BODEGA_LIST_RESET = "BODEGA_LIST_RESET";

export const BODEGA_CREATE_REQUEST = "BODEGA_CREATE_REQUEST";
export const BODEGA_CREATE_SUCCESS = "BODEGA_CREATE_SUCCESS";
export const BODEGA_CREATE_FAIL = "BODEGA_CREATE_FAIL";

export const BODEGA_DETAILS_REQUEST = "BODEGA_DETAILS_REQUEST";
export const BODEGA_DETAILS_SUCCESS = "BODEGA_DETAILS_SUCCESS";
export const BODEGA_DETAILS_FAIL = "BODEGA_DETAILS_FAIL";
export const BODEGA_DETAILS_RESET = "BODEGA_DETAILS_RESET";

export const BODEGA_UPDATE_REQUEST = "BODEGA_UPDATE_REQUEST";
export const BODEGA_UPDATE_SUCCESS = "BODEGA_UPDATE_SUCCESS";
export const BODEGA_UPDATE_FAIL = "BODEGA_UPDATE_FAIL";
export const BODEGA_UPDATE_RESET = "BODEGA_UPDATE_RESET";

export const BODEGA_DELETE_REQUEST = "BODEGA_DELETE_REQUEST";
export const BODEGA_DELETE_SUCCESS = "BODEGA_DELETE_SUCCESS";
export const BODEGA_DELETE_FAIL = "BODEGA_DELETE_FAIL";
export const BODEGA_DELETE_RESET = "BODEGA_DELETE_RESET";

export const BODEGA_ACTIVATE_REQUEST = "BODEGA_ACTIVATE_REQUEST";
export const BODEGA_ACTIVATE_SUCCESS = "BODEGA_ACTIVATE_SUCCESS";
export const BODEGA_ACTIVATE_FAIL = "BODEGA_ACTIVATE_FAIL";
export const BODEGA_ACTIVATE_RESET = "BODEGA_ACTIVATE_RESET";