
export const CLAVE_UPDATE_REQUEST = "CLAVE_UPDATE_REQUEST";
export const CLAVE_UPDATE_SUCCESS = "CLAVE_UPDATE_SUCCESS";
export const CLAVE_UPDATE_FAIL = "CLAVE_UPDATE_FAIL";
export const CLAVE_UPDATE_RESET = "CLAVE_UPDATE_RESET";