export const COMBO_CIUDADES_LIST_REQUEST = "COMBO_CIUDADES_LIST_REQUEST";
export const COMBO_CIUDADES_LIST_SUCCESS = "COMBO_CIUDADES_LIST_SUCCESS";
export const COMBO_CIUDADES_LIST_FAIL = "COMBO_CIUDADES_LIST_FAIL";
export const COMBO_CIUDADES_LIST_RESET = "COMBO_CIUDADES_LIST_RESET";