export const COMBO_USUARIOS_TALLER_LIST_REQUEST = "COMBO_USUARIOS_TALLER_LIST_REQUEST";
export const COMBO_USUARIOS_TALLER_LIST_SUCCESS = "COMBO_USUARIOS_TALLER_LIST_SUCCESS";
export const COMBO_USUARIOS_TALLER_LIST_FAIL = "COMBO_USUARIOS_TALLER_LIST_FAIL";
export const COMBO_USUARIOS_TALLER_LIST_RESET = "COMBO_USUARIOS_TALLER_LIST_RESET";