export const COMBO_DISPOSITIVOS_LIST_REQUEST = "COMBO_DISPOSITIVOS_LIST_REQUEST";
export const COMBO_DISPOSITIVOS_LIST_SUCCESS = "COMBO_DISPOSITIVOS_LIST_SUCCESS";
export const COMBO_DISPOSITIVOS_LIST_FAIL = "COMBO_DISPOSITIVOS_LIST_FAIL";
export const COMBO_DISPOSITIVOS_LIST_RESET = "COMBO_DISPOSITIVOS_LIST_RESET";