export const COMBO_PLANES_LIST_REQUEST = "COMBO_PLANES_LIST_REQUEST";
export const COMBO_PLANES_LIST_SUCCESS = "COMBO_PLANES_LIST_SUCCESS";
export const COMBO_PLANES_LIST_FAIL = "COMBO_PLANES_LIST_FAIL";
export const COMBO_PLANES_LIST_RESET = "COMBO_PLANES_LIST_RESET";

export const PLANES_CREATE_FAIL = "PLANES_CREATE_FAIL";
export const PLANES_CREATE_REQUEST = "PLANES_CREATE_REQUEST";
export const PLANES_CREATE_SUCCESS = "PLANES_CREATE_SUCCESS";