//CUADRO 1
export const DASHBOARD_LIST_REQUEST = "DASHBOARD_LIST_REQUEST";
export const DASHBOARD_LIST_SUCCESS = "DASHBOARD_LIST_SUCCESS";
export const DASHBOARD_LIST_FAIL = "DASHBOARD_LIST_FAIL";
export const DASHBOARD_LIST_RESET = "DASHBOARD_LIST_RESET";
//CUADRO 2
export const DASHBOARDC2_LIST_REQUEST = "DASHBOARDC2_LIST_REQUEST";
export const DASHBOARDC2_LIST_SUCCESS = "DASHBOARDC2_LIST_SUCCESS";
export const DASHBOARDC2_LIST_FAIL = "DASHBOARDC2_LIST_FAIL";
export const DASHBOARDC2_LIST_RESET = "DASHBOARDC2_LIST_RESET";
//CUADRO 3
export const DASHBOARDC3_LIST_REQUEST = "DASHBOARDC3_LIST_REQUEST";
export const DASHBOARDC3_LIST_SUCCESS = "DASHBOARDC3_LIST_SUCCESS";
export const DASHBOARDC3_LIST_FAIL = "DASHBOARDC3_LIST_FAIL";
export const DASHBOARDC3_LIST_RESET = "DASHBOARDC3_LIST_RESET";
//CUADRO 4
export const DASHBOARDC4_LIST_REQUEST = "DASHBOARDC4_LIST_REQUEST";
export const DASHBOARDC4_LIST_SUCCESS = "DASHBOARDC4_LIST_SUCCESS";
export const DASHBOARDC4_LIST_FAIL = "DASHBOARDC4_LIST_FAIL";
export const DASHBOARDC4_LIST_RESET = "DASHBOARDC4_LIST_RESET";
//LINECHART DATA
export const DASHBOARDLINEDATA_LIST_REQUEST = "DASHBOARDLINEDATA_LIST_REQUEST";
export const DASHBOARDLINEDATA_LIST_SUCCESS = "DASHBOARDLINEDATA_LIST_SUCCESS";
export const DASHBOARDLINEDATA_LIST_FAIL = "DASHBOARDLINEDATA_LIST_FAIL";
export const DASHBOARDLINEDATA_LIST_RESET = "DASHBOARDLINEDATA_LIST_RESET";