export const DISPOSITIVOS_LIST_REQUEST = "DISPOSITIVOS_LIST_REQUEST";
export const DISPOSITIVOS_LIST_SUCCESS = "DISPOSITIVOS_LIST_SUCCESS";
export const DISPOSITIVOS_LIST_FAIL = "DISPOSITIVOS_LIST_FAIL";
export const DISPOSITIVOS_LIST_RESET = "DISPOSITIVOS_LIST_RESET";

export const DISPOSITIVOS_CREATE_REQUEST = "DISPOSITIVOS_CREATE_REQUEST";
export const DISPOSITIVOS_CREATE_SUCCESS = "DISPOSITIVOS_CREATE_SUCCESS";
export const DISPOSITIVOS_CREATE_FAIL = "DISPOSITIVOS_CREATE_FAIL";

export const DISPOSITIVOS_DETAILS_REQUEST = "DISPOSITIVOS_DETAILS_REQUEST";
export const DISPOSITIVOS_DETAILS_SUCCESS = "DISPOSITIVOS_DETAILS_SUCCESS";
export const DISPOSITIVOS_DETAILS_FAIL = "DISPOSITIVOS_DETAILS_FAIL";
export const DISPOSITIVOS_DETAILS_RESET = "DISPOSITIVOS_DETAILS_RESET";

export const DISPOSITIVOS_UPDATE_REQUEST = "DISPOSITIVOS_UPDATE_REQUEST";
export const DISPOSITIVOS_UPDATE_SUCCESS = "DISPOSITIVOS_UPDATE_SUCCESS";
export const DISPOSITIVOS_UPDATE_FAIL = "DISPOSITIVOS_UPDATE_FAIL";
export const DISPOSITIVOS_UPDATE_RESET = "DISPOSITIVOS_UPDATE_RESET";

export const DISPOSITIVOS_DELETE_REQUEST = "DISPOSITIVOS_DELETE_REQUEST";
export const DISPOSITIVOS_DELETE_SUCCESS = "DISPOSITIVOS_DELETE_SUCCESS";
export const DISPOSITIVOS_DELETE_FAIL = "DISPOSITIVOS_DELETE_FAIL";
export const DISPOSITIVOS_DELETE_RESET = "DISPOSITIVOS_DELETE_RESET";