//CUADRO 1
export const ERRORREDIRECT_LIST_REQUEST = "ERRORREDIRECT_LIST_REQUEST";
export const ERRORREDIRECT_LIST_SUCCESS = "ERRORREDIRECT_LIST_SUCCESS";
export const ERRORREDIRECT_LIST_FAIL = "ERRORREDIRECT_LIST_FAIL";
export const ERRORREDIRECT_LIST_RESET = "ERRORREDIRECT_LIST_RESET";