export const IMG_LIST_REQUEST = "IMG_LIST_REQUEST";
export const IMG_LIST_SUCCESS = "IMG_LIST_SUCCESS";
export const IMG_LIST_FAIL = "IMG_LIST_FAIL";
export const IMG_LIST_RESET = "IMG_LIST_RESET";

export const IMG_CREATE_REQUEST = "IMG_CREATE_REQUEST";
export const IMG_CREATE_SUCCESS = "IMG_CREATE_SUCCESS";
export const IMG_CREATE_FAIL = "#IMG_CREATE_FAIL";

export const IMG_DETAILS_REQUEST = "IMG_DETAILS_REQUEST";
export const IMG_DETAILS_SUCCESS = "IMG_DETAILS_SUCCESS";
export const IMG_DETAILS_FAIL = "IMG_DETAILS_FAIL";
export const IMG_DETAILS_RESET = "IMG_DETAILS_RESET";

export const IMG_UPDATE_REQUEST = "IMG_UPDATE_REQUEST";
export const IMG_UPDATE_SUCCESS = "IMG_UPDATE_SUCCESS";
export const IMG_UPDATE_FAIL = "IMG_UPDATE_FAIL";
export const IMG_UPDATE_RESET = "IMG_UPDATE_RESET";

export const IMG_DELETE_REQUEST = "IMG_DELETE_REQUEST";
export const IMG_DELETE_SUCCESS = "IMG_DELETE_SUCCESS";
export const IMG_DELETE_FAIL = "IMG_DELETE_FAIL";
export const IMG_DELETE_RESET = "IMG_DELETE_RESET";