export const PERFIL_LIST_REQUEST = "PERFIL_LIST_REQUEST";
export const PERFIL_LIST_SUCCESS = "PERFIL_LIST_SUCCESS";
export const PERFIL_LIST_FAIL = "PERFIL_LIST_FAIL";
export const PERFIL_LIST_RESET = "PERFIL_LIST_RESET";

export const PERFIL_CREATE_REQUEST = "PERFIL_CREATE_REQUEST";
export const PERFIL_CREATE_SUCCESS = "PERFIL_CREATE_SUCCESS";
export const PERFIL_CREATE_FAIL = "PERFIL_CREATE_FAIL";

export const PERFIL_DETAILS_REQUEST = "PERFIL_DETAILS_REQUEST";
export const PERFIL_DETAILS_SUCCESS = "PERFIL_DETAILS_SUCCESS";
export const PERFIL_DETAILS_FAIL = "PERFIL_DETAILS_FAIL";
export const PERFIL_DETAILS_RESET = "PERFIL_DETAILS_RESET";

export const PERFIL_UPDATE_REQUEST = "PERFIL_UPDATE_REQUEST";
export const PERFIL_UPDATE_SUCCESS = "PERFIL_UPDATE_SUCCESS";
export const PERFIL_UPDATE_FAIL = "PERFIL_UPDATE_FAIL";
export const PERFIL_UPDATE_RESET = "PERFIL_UPDATE_RESET";

export const PERFIL_DELETE_REQUEST = "PERFIL_DELETE_REQUEST";
export const PERFIL_DELETE_SUCCESS = "PERFIL_DELETE_SUCCESS";
export const PERFIL_DELETE_FAIL = "PERFIL_DELETE_FAIL";
export const PERFIL_DELETE_RESET = "PERFIL_DELETE_RESET";