export const PLANES_LIST_REQUEST = "PLANES_LIST_REQUEST";
export const PLANES_LIST_SUCCESS = "PLANES_LIST_SUCCESS";
export const PLANES_LIST_FAIL = "PLANES_LIST_FAIL";
export const PLANES_LIST_RESET = "PLANES_LIST_RESET";

export const PLANES_CREATE_REQUEST = "PLANES_CREATE_REQUEST";
export const PLANES_CREATE_SUCCESS = "PLANES_CREATE_SUCCESS";
export const PLANES_CREATE_FAIL = "PLANES_CREATE_FAIL";

export const PLANES_DETAILS_REQUEST = "PLANES_DETAILS_REQUEST";
export const PLANES_DETAILS_SUCCESS = "PLANES_DETAILS_SUCCESS";
export const PLANES_DETAILS_FAIL = "PLANES_DETAILS_FAIL";
export const PLANES_DETAILS_RESET = "PLANES_DETAILS_RESET";

export const PLANES_UPDATE_REQUEST = "PLANES_UPDATE_REQUEST";
export const PLANES_UPDATE_SUCCESS = "PLANES_UPDATE_SUCCESS";
export const PLANES_UPDATE_FAIL = "PLANES_UPDATE_FAIL";
export const PLANES_UPDATE_RESET = "PLANES_UPDATE_RESET";

export const PLANES_DELETE_REQUEST = "PLANES_DELETE_REQUEST";
export const PLANES_DELETE_SUCCESS = "PLANES_DELETE_SUCCESS";
export const PLANES_DELETE_FAIL = "PLANES_DELETE_FAIL";
export const PLANES_DELETE_RESET = "PLANES_DELETE_RESET";

export const PLANES_ACTIVATE_REQUEST = "PLANES_ACTIVATE_REQUEST";
export const PLANES_ACTIVATE_SUCCESS = "PLANES_ACTIVATE_SUCCESS";
export const PLANES_ACTIVATE_FAIL = "PLANES_ACTIVATE_FAIL";
export const PLANES_ACTIVATE_RESET = "PLANES_ACTIVATE_RESET";