export const PRODUCTO_LIST_REQUEST = "PRODUCTO_LIST_REQUEST";
export const PRODUCTO_LIST_SUCCESS = "PRODUCTO_LIST_SUCCESS";
export const PRODUCTO_LIST_FAIL = "PRODUCTO_LIST_FAIL";
export const PRODUCTO_LIST_RESET = "CPRODUCTO_LIST_RESET";

export const PRODUCTO_CREATE_REQUEST = "PRODUCTO_CREATE_REQUEST";
export const PRODUCTO_CREATE_SUCCESS = "PRODUCTO_CREATE_SUCCESS";
export const PRODUCTO_CREATE_FAIL = "PRODUCTO_CREATE_FAIL";

export const PRODUCTO_DETAILS_REQUEST = "PRODUCTO_DETAILS_REQUEST";
export const PRODUCTO_DETAILS_SUCCESS = "PRODUCTO_DETAILS_SUCCESS";
export const PRODUCTO_DETAILS_FAIL = "PRODUCTO_DETAILS_FAIL";
export const PRODUCTO_DETAILS_RESET = "PRODUCTO_DETAILS_RESET";

export const PRODUCTO_UPDATE_REQUEST = "PRODUCTO_UPDATE_REQUEST";
export const PRODUCTO_UPDATE_SUCCESS = "PRODUCTO_UPDATE_SUCCESS";
export const PRODUCTO_UPDATE_FAIL = "PRODUCTO_UPDATE_FAIL";
export const PRODUCTO_UPDATE_RESET = "PRODUCTO_UPDATE_RESET";

export const PRODUCTO_DELETE_REQUEST = "PRODUCTO_DELETE_REQUEST";
export const PRODUCTO_DELETE_SUCCESS = "PRODUCTO_DELETE_SUCCESS";
export const PRODUCTO_DELETE_FAIL = "PRODUCTO_DELETE_FAIL";
export const PRODUCTO_DELETE_RESET = "PRODUCTO_DELETE_RESET";

export const PRODUCTO_ACTIVATE_REQUEST = "PRODUCTO_ACTIVATE_REQUEST";
export const PRODUCTO_ACTIVATE_SUCCESS = "PRODUCTO_ACTIVATE_SUCCESS";
export const PRODUCTO_ACTIVATE_FAIL = "PRODUCTO_ACTIVATE_FAIL";
export const PRODUCTO_ACTIVATE_RESET = "PRODUCTO_ACTIVATE_RESET";