export const REGION_LIST_REQUEST = "REGION_LIST_REQUEST";
export const REGION_LIST_SUCCESS = "REGION_LIST_SUCCESS";
export const REGION_LIST_FAIL = "REGION_LIST_FAIL";
export const REGION_LIST_RESET = "REGION_LIST_RESET";