
export const ENTREGA_UPDATE_REQUEST = "ENTREGA_UPDATE_REQUEST";
export const ENTREGA_UPDATE_SUCCESS = "ENTREGA_UPDATE_SUCCESS";
export const ENTREGA_UPDATE_FAIL = "ENTREGA_UPDATE_FAIL";
export const ENTREGA_UPDATE_RESET = "ENTREGA_UPDATE_RESET";