export const REPORTES_LIST_REQUEST = "REPORTES_LIST_REQUEST";
export const REPORTES_LIST_SUCCESS = "REPORTES_LIST_SUCCESS";
export const REPORTES_LIST_FAIL = "REPORTES_LIST_FAIL";
export const REPORTES_LIST_RESET = "CREPORTES_LIST_RESET";

export const REPORTES_CREATE_REQUEST = "REPORTES_CREATE_REQUEST";
export const REPORTES_CREATE_SUCCESS = "REPORTES_CREATE_SUCCESS";
export const REPORTES_CREATE_FAIL = "REPORTES_CREATE_FAIL";

export const REPORTES_DETAILS_REQUEST = "REPORTES_DETAILS_REQUEST";
export const REPORTES_DETAILS_SUCCESS = "REPORTES_DETAILS_SUCCESS";
export const REPORTES_DETAILS_FAIL = "REPORTES_DETAILS_FAIL";
export const REPORTES_DETAILS_RESET = "REPORTES_DETAILS_RESET";

export const REPORTES_UPDATE_REQUEST = "REPORTES_UPDATE_REQUEST";
export const REPORTES_UPDATE_SUCCESS = "REPORTES_UPDATE_SUCCESS";
export const REPORTES_UPDATE_FAIL = "REPORTES_UPDATE_FAIL";
export const REPORTES_UPDATE_RESET = "REPORTES_UPDATE_RESET";

export const REPORTES_DELETE_REQUEST = "REPORTES_DELETE_REQUEST";
export const REPORTES_DELETE_SUCCESS = "REPORTES_DELETE_SUCCESS";
export const REPORTES_DELETE_FAIL = "REPORTES_DELETE_FAIL";
export const REPORTES_DELETE_RESET = "REPORTES_DELETE_RESET";