export const SOLICITUD_LIST_REQUEST = "SOLICITUD_LIST_REQUEST";
export const SOLICITUD_LIST_SUCCESS = "SOLICITUD_LIST_SUCCESS";
export const SOLICITUD_LIST_FAIL = "SOLICITUD_LIST_FAIL";
export const SOLICITUD_LIST_RESET = "SOLICITUD_LIST_RESET";

export const SOLICITUD_CREATE_REQUEST = "SOLICITUD_CREATE_REQUEST";
export const SOLICITUD_CREATE_SUCCESS = "SOLICITUD_CREATE_SUCCESS";
export const SOLICITUD_CREATE_FAIL = "SOLICITUD_CREATE_FAIL";

export const SOLICITUD_DETAILS_REQUEST = "SOLICITUD_DETAILS_REQUEST";
export const SOLICITUD_DETAILS_SUCCESS = "SOLICITUD_DETAILS_SUCCESS";
export const SOLICITUD_DETAILS_FAIL = "SOLICITUD_DETAILS_FAIL";
export const SOLICITUD_DETAILS_RESET = "SOLICITUD_DETAILS_RESET";

export const SOLICITUD_UPDATE_REQUEST = "SOLICITUD_UPDATE_REQUEST";
export const SOLICITUD_UPDATE_SUCCESS = "SOLICITUD_UPDATE_SUCCESS";
export const SOLICITUD_UPDATE_FAIL = "SOLICITUD_UPDATE_FAIL";
export const SOLICITUD_UPDATE_RESET = "SOLICITUD_UPDATE_RESET";

export const SOLICITUD_DELETE_REQUEST = "SOLICITUD_DELETE_REQUEST";
export const SOLICITUD_DELETE_SUCCESS = "SOLICITUD_DELETE_SUCCESS";
export const SOLICITUD_DELETE_FAIL = "SOLICITUD_DELETE_FAIL";
export const SOLICITUD_DELETE_RESET = "SOLICITUD_DELETE_RESET";