export const SOLICITUDM_LIST_REQUEST = "SOLICITUDM_LIST_REQUEST";
export const SOLICITUDM_LIST_SUCCESS = "SOLICITUDM_LIST_SUCCESS";
export const SOLICITUDM_LIST_FAIL = "SOLICITUDM_LIST_FAIL";
export const SOLICITUDM_LIST_RESET = "SOLICITUDM_LIST_RESET";

export const SOLICITUDM_CREATE_REQUEST = "SOLICITUDM_CREATE_REQUEST";
export const SOLICITUDM_CREATE_SUCCESS = "SOLICITUDM_CREATE_SUCCESS";
export const SOLICITUDM_CREATE_FAIL = "SOLICITUDM_CREATE_FAIL";

export const SOLICITUDM_DETAILS_REQUEST = "SOLICITUDM_DETAILS_REQUEST";
export const SOLICITUDM_DETAILS_SUCCESS = "SOLICITUDM_DETAILS_SUCCESS";
export const SOLICITUDM_DETAILS_FAIL = "SOLICITUDM_DETAILS_FAIL";
export const SOLICITUDM_DETAILS_RESET = "SOLICITUDM_DETAILS_RESET";

export const SOLICITUDM_UPDATE_REQUEST = "SOLICITUDM_UPDATE_REQUEST";
export const SOLICITUDM_UPDATE_SUCCESS = "SOLICITUDM_UPDATE_SUCCESS";
export const SOLICITUDM_UPDATE_FAIL = "SOLICITUDM_UPDATE_FAIL";
export const SOLICITUDM_UPDATE_RESET = "SOLICITUDM_UPDATE_RESET";

export const SOLICITUDM_DELETE_REQUEST = "SOLICITUDM_DELETE_REQUEST";
export const SOLICITUDM_DELETE_SUCCESS = "SOLICITUDM_DELETE_SUCCESS";
export const SOLICITUDM_DELETE_FAIL = "SOLICITUDM_DELETE_FAIL";
export const SOLICITUDM_DELETE_RESET = "SOLICITUDM_DELETE_RESET";