export const SUCURSALES_LIST_REQUEST = "SUCURSALES_LIST_REQUEST";
export const SUCURSALES_LIST_SUCCESS = "SUCURSALES_LIST_SUCCESS";
export const SUCURSALES_LIST_FAIL = "SUCURSALES_LIST_FAIL";
export const SUCURSALES_LIST_RESET = "SUCURSALES_LIST_RESET";