export const SUPERVISOR_LIST_REQUEST = "SUPERVISOR_LIST_REQUEST";
export const SUPERVISOR_LIST_SUCCESS = "SUPERVISOR_LIST_SUCCESS";
export const SUPERVISOR_LIST_FAIL = "SUPERVISOR_LIST_FAIL";
export const SUPERVISOR_LIST_RESET = "SUPERVISOR_LIST_RESET";

export const SUPERVISOR_CREATE_REQUEST = "SUPERVISOR_CREATE_REQUEST";
export const SUPERVISOR_CREATE_SUCCESS = "SUPERVISOR_CREATE_SUCCESS";
export const SUPERVISOR_CREATE_FAIL = "SUPERVISOR_CREATE_FAIL";

export const SUPERVISOR_DETAILS_REQUEST = "SUPERVISOR_DETAILS_REQUEST";
export const SUPERVISOR_DETAILS_SUCCESS = "SUPERVISOR_DETAILS_SUCCESS";
export const SUPERVISOR_DETAILS_FAIL = "SUPERVISOR_DETAILS_FAIL";
export const SUPERVISOR_DETAILS_RESET = "SUPERVISOR_DETAILS_RESET";

export const SUPERVISOR_UPDATE_REQUEST = "SUPERVISOR_UPDATE_REQUEST";
export const SUPERVISOR_UPDATE_SUCCESS = "SUPERVISOR_UPDATE_SUCCESS";
export const SUPERVISOR_UPDATE_FAIL = "SUPERVISOR_UPDATE_FAIL";
export const SUPERVISOR_UPDATE_RESET = "SUPERVISOR_UPDATE_RESET";

export const SUPERVISOR_DELETE_REQUEST = "SUPERVISOR_DELETE_REQUEST";
export const SUPERVISOR_DELETE_SUCCESS = "SUPERVISOR_DELETE_SUCCESS";
export const SUPERVISOR_DELETE_FAIL = "SUPERVISOR_DELETE_FAIL";
export const SUPERVISOR_DELETE_RESET = "SUPERVISOR_DELETE_RESET";